### ISSUE TITLE
yeoman 1.0

### ISSUE THREAD

**Issue by bbn** [hoodiehq-archive/hood.ie-website-old#10]
The latest version of yeoman is 1.0, and it is not compatible with 0.9.6. Would be good to either update this site to use the latest, or else add a line explaining how to install yeoman 0.9.6. (I know it's not difficult. For a neophyte like me it took some digging.)

**Comment by bbn** [comment]
furthermore, yeoman 0.9.6 doesn't seem to be working on my comp. might have to do with the version of python I have on my system.

```
/usr/local/bin/_yeomaninsight:149: Warning: 'as' will become a reserved keyword in Python 2.6
  File "/usr/local/bin/_yeomaninsight", line 149
    except URLError as e:
                     ^
SyntaxError: invalid syntax
```

I enjoy the irony that it's the bug reporting system that is causing the bug. :)

Ok, since I can't get the build process going here I will make another issue to help with the documentation.

**Comment by gr2m** [comment]
yes, upgrading to yeoman 1.0 & grunt 0.4 is kinda overdue, sorry for that, it's not a top priority at the moment. But if fancy, feel free to do it yourself, any pull request is much appreciated.

**Comment by espy** [comment]
Oh, I did this yesterday.
