### ISSUE TITLE
more thorough store API documentation

### ISSUE THREAD

**Issue by bbn** [hoodiehq-archive/hood.ie-website-old#12]
(I know these are all planned things. But may as well make an issue out of it. I'd be happy to contribute if I could get the build system working ;) )

More thorough documentation of the store api. In particular, some discussion of the continuations available through $.Deferred.

**Comment by bbn** [comment]
actually never mind, i see that the done() continuation is present in the documentation already. not sure how i missed that.

**Comment by gr2m** [comment]
thanks anyway for looking into it, Ben! Let me know if you have any questions
