### ISSUE TITLE
JSON vs JavaScript object

### ISSUE THREAD

**Issue by xMartin** [hoodiehq-archive/hood.ie-website-old#24]
On the home page it says:

> As you can see, the documents you store need a type and some JSON data. Both are arbitrary and don't need to be set up anywhere previously. As long as you give Hoodie valid JSON, it will eat anything.

But in the example there is no JSON, just a JavaScript object. Might be nit-picking but as it is emphasized that it needs to be _valid_ JSON I find it a bit confusing. It is also not clear to me if I can pass a JSON string or a JavaScript object or if it needs to be a JavaScript object.

**Comment by janl** [comment]
A very good nitpick :D

I’m waiting for @espy to help me set up the website toolchain, so I can fix that. Or if you want to send a pull request, be our guest :)

**Comment by xMartin** [comment]
So looks as if it needs to be a JavaScript object. The text could be something like that:

> Just pass an object for your data. This will be stored as JSON.

See also https://github.com/hoodiehq/hoodie.js/issues/90

**Comment by gr2m** [comment]
that's great, thanks Martin!

**Comment by espy** [comment]
Done, thanks a lot!
