### ISSUE TITLE
fix blog performance

### ISSUE THREAD

**Issue by svnlto** [hoodiehq-archive/hood.ie-website-old#27]
Without going on a rant here, I let this image speak for itself. This is a call to the blogs root.

![hoodie blog request fail](http://f.cl.ly/items/3f2d0o3j3U273U3V1o0e/Screen%20Shot%202013-07-29%20at%2012.35.10.png)

Pushing down 12+ MB on first visit is a bit much. I'm pretty sure we can do better than this.

**Comment by svnlto** [comment]
Having had a closer look at this, I believe it's the twitter embeds that are responsible for about 10MB of the above 12.

**Comment by janl** [comment]
holy smokes.

**Comment by espy** [comment]
I've seen this too, it's on my list, I'm re-doing much of the blog anyway.

**Comment by espy** [comment]
We're currently down to about 6MB on the main page, half of that being images. 2.2MB are Vimeo being stupid and preloading a video before anyone clicked anything. 

Solutions:
- [ ] **Everyone:** Use Wordpress' more-tag to expose less images on the start/overview pages (e.g. only the first one per post), possibly with videos always after the fold
- [ ] **Me:** install adaptiveImages.php to automatically serve smaller images to smaller screens
