### ISSUE TITLE
Tweaks to Ubuntu installation instructions

### ISSUE THREAD

**Issue by stuartlangridge** [hoodiehq-archive/hood.ie-website-old#28]
A few suggested tweaks to the installation instructions for Ubuntu for hoodie.

CouchDB installation
http://hood.ie/#installation suggests to install couchdb. I recommend installing couchdb-bin; couchdb-bin is all the actual couch stuff; "couchdb" is the few scripts that make couch start up on machine start, which you don't want. So, propose 

$ sudo apt-get update
$ sudo apt-get install couchdb-bin

node installation
http://hood.ie/#installation suggests to build node from source. Chris Lea does a good job running a PPA (personal package archive) for Ubuntu for the latest node, and installing from a PPA is a good idea here; you get the latest node upgrades as part of your normal system upgrades that way, and you don't need to have all the build tools required to build node from source. These instructions are Ubuntu-specific. So, propose:

Then, add Chris Lea's Node.js PPA and install from it:
$ sudo add-apt-repository ppa:chris-lea/node.js
$ sudo apt-get update
$ sudo apt-get install nodejs

**Comment by janl** [comment]
Great! Wanna send a PR? :)

**Comment by espy** [comment]
@stuartlangridge Thanks for writing that up, but you don't have to bother with the PR. I'm thinking of having separate tabs for different distros on hood.ie anyway, so I'll just do that myself :)

**Comment by espy** [comment]
Done with https://github.com/hoodiehq/hood.ie/commit/e1d616a2bc14e1df72285b1a48a403e2fb329ce5

**Comment by svnlto** [comment]
@espy great idea. <3
