### ISSUE TITLE
Get docs from actual repos instead of maintaining them multiple times

### ISSUE THREAD

**Issue by espy** [hoodiehq-archive/hood.ie-website-old#35]
Idea: have some empty `<div class="replaceWithDocs" data-origin="gh-pagesURLOfRepo" data-id="elementWithTheDocsWeWant"></div>` in hood.ie, $.load() all the referenced docs pages, pluck the respective elements from them and insert them in place of the placeholders.

This way, both the repos themselves and the hood.ie page will always up to date docs.

**Comment by janl** [comment]
Alternatively, make docs a separate repo and link to that and only keep some very minimal examples to show off on the front page

**Comment by zoepage** [comment]
closed in fav of https://github.com/hoodiehq/documentation/issues/19
