### ISSUE TITLE
Add export COUCH_URL to docs

### ISSUE THREAD

**Issue by martin-hewitt** [hoodiehq-archive/hood.ie-website-old#38]
I've already got CouchDB installed, and was trying to work out how to tell Hoodie where it lives.

In a ticket against the main Hoodie repo, I found the environment variable COUCH_URL, which works perfectly, but I couldn't find it documented anywhere.

For those coming to Hoodie via CouchDB, just a line somewhere about this config value could make the Getting Started process a wee bit easier.

**Comment by janl** [comment]
In theory, you should not need `COUCH_URL` anywhere. On Windows you need it today, but I hop to get that fixed this week. COUCH_URL is generally only a workaround for local installations as Hoodie should auto detect where your CouchDB lives (modulo that working perfectly, which it doesn’t quite yet :).

**Comment by martin-hewitt** [comment]
Ah, cool. It didn't work on my (local) machine, is there any info I can give that would help with working out why? Or is it just likely than I'm an edge case and I'll use `COUCH_URL` in the meantime?

**Comment by martin-hewitt** [comment]
Also, i guess if I'm using, say, Heroku and Cloudant, I'll have to use `COUCH_URL` in the former to use the latter?

**Comment by janl** [comment]
What is your system configuration? And how did you install the respective dependencies?

As for deployment, COUCH_URL is required and documented in the my-first-hoodie README for Nodejitsu. We don't official support Heroku or Cloudant yet, but any work or success reports there would be more than welcome :)

We are planning to make things even easier for deployment, too, so this will be all seamless :)

**Comment by martin-hewitt** [comment]
I'm on Mac OS X Mavericks, and I followed the Hood.ie install guide and used homebrew to install all the dependencies, which all installed fine, except for the issue that CouchDB wouldn't start, so I then downloaded CouchDB from the official website, which started fine. 

Hoodie kept trying to start CouchDB, and didn't see the startup crash/errors, so timed out. Once I'd overrode with the environment variable, all worked perfectly.

I'll be deploying on Heroku & Cloudant as a dev system by the end of the week, so I'll report back.

**Comment by janl** [comment]
Too bad that the Homebrew install didn't work out. We should find out what that is. In the meantime, you will have to use COUCH_URL with the CouchDB.app until the fix I mentioned earlier is in (it should address all platforms).

**Comment by martin-hewitt** [comment]
Cool, I'll hop on the CouchDB ML and see if anyone recognises the crash output.

**Comment by janl** [comment]
Feel free to paste here. I'm doing things to CouchDB that are atypical. So they will likely not have seen things. Or suggest the wrong fixes.

I'll be in the air most of today, but will check ASAP :)

**Comment by martin-hewitt** [comment]
Not sure if it's a bug in the formula for CouchDB, but the error is:

```
martinhewitt$ couchdb

=CRASH REPORT==== 11-Nov-2013::13:58:57 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.30.0>
    registered_name: []
    exception exit: {{app_would_not_start,ssl},
                     {couch_app,start,
                                [normal,
                                 ["/usr/local/etc/couchdb/default.ini",
                                  "/usr/local/etc/couchdb/local.ini"]]}}
      in function  application_master:init/4 (application_master.erl, line 133)
    ancestors: [<0.29.0>]
    messages: [{'EXIT',<0.31.0>,normal}]
    links: [<0.29.0>,<0.7.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 149
  neighbours:

=INFO REPORT==== 11-Nov-2013::13:58:57 ===
    application: couch
    exited: {{app_would_not_start,ssl},
             {couch_app,start,
                        [normal,
                         ["/usr/local/etc/couchdb/default.ini",
                          "/usr/local/etc/couchdb/local.ini"]]}}
    type: temporary
```

And the only ref I can find to this is in this ticket: https://issues.apache.org/jira/browse/COUCHDB-1833 about CouchDB having compatibility and dependency issues with ERLang. The `brew install couchdb` command installed RB1602.

**Comment by martin-hewitt** [comment]
Also had an issue with the Mac CouchDB app when signing up, which I've logged here: https://github.com/hoodiehq/hoodie.js/issues/170

Using an old VM with CouchDB 1.2.0 works nicely, though, and I'm making good progress!

**Comment by janl** [comment]
closing in favour of https://github.com/hoodiehq/documentation/issues/15
