### ISSUE TITLE
How do I build this?

### ISSUE THREAD

**Issue by janl** [hoodiehq-archive/hood.ie-website-old#4]
@espy how do I build the website?

**Comment by espy** [comment]
Yeoman 0.9.6. So just `$ yeoman server`, make your changes in master, `$ yeoman build` and then do the regular push to master and the subtree push to gh-pages described in the readme.

**Comment by janl** [comment]
Cool, got it, added it to the readme as well.

Now I am stuck here:

```
> git subtree push --prefix dist origin g-pages
git: 'subtree' is not a git command. See 'git --help'.
```

**Comment by janl** [comment]
Ich installier mal git 1.8.x

**Comment by janl** [comment]
ok, I have git subtree now, but it says:

```
'dist' does not exist; use 'git subtree add'
```

https://github.com/yeoman/yeoman/wiki/Deployment doesn’t make this obvious either. Sorry!

**Comment by janl** [comment]
README got updated.
