### ISSUE TITLE
Instructions of installation on Fedora 19 (and newer)

### ISSUE THREAD

**Issue by avsej** [hoodiehq-archive/hood.ie-website-old#40]
Fedora 19 is [current supported release](https://fedoraproject.org/wiki/Releases#Current_Supported_Releases)

```
First, install CouchDB (1.2.x or newer), git and node.js. On Fedora 19+:

  $ sudo yum install couchdb git nodejs npm

Now you can install Hoodie using Node's package manager:

  $ sudo npm install -g hoodie-cli

Installation done! Time to build apps.
```

Software versions in today's fedora 19:

```
$ node --version
v0.10.21
$ npm --version
1.3.6
$ couchdb -V | head -n1
couchdb - Apache CouchDB 1.3.1
```

**Comment by janl** [comment]
Thanks! :)

Do you feel like seining a PR? The information is stored in build/app/index.html

**Comment by avsej** [comment]
It would be easier if you will just add that into proper place of that HTML

**Comment by janl** [comment]
0cool, will do, just wanted to check if you preferred doing this :)

**Comment by zoepage** [comment]
closed in fav of https://github.com/hoodiehq/documentation/issues/16
