### ISSUE TITLE
use grunt gh-pages for simpler deployement

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/hood.ie-website-old#43]
https://github.com/tschaub/grunt-gh-pages

**Comment by gr2m** [comment]
See my setup here:
https://github.com/gr2m/hood.ie_playground

It's really, really simple to update stuff & deploy it. Happy to put that in.

**Comment by espy** [comment]
Ah damn, I still haven't gotten around to this, sorry. Please go ahead if you have the time!
