### ISSUE TITLE
Document hoodie.id()

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/hood.ie-website-old#47]
We now have a new API: `hoodie.id()`.

`hoodie.id()` generates a random ID that is unique to the current user, independent of whether the user has an account or not. It persists in between page reloads and will be written in the `_users` doc once the user signs up. It's also the ID that is stored with every object in the `createdBy` property.

**Comment by zoepage** [comment]
closing in fav of https://github.com/hoodiehq/documentation/issues/13
