### ISSUE TITLE
Add a Merchandise section

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/hood.ie-website-old#48]
We won't start selling merch anytime soon, but we can still announce it and have interested people sign up for our newsletter.

People [seem](https://twitter.com/skohler/status/435344542943150080) [to](https://twitter.com/PascalPrecht/status/435344183382253568) [like](https://twitter.com/buk/status/435348870533750784) our cap & stickers :)

**Comment by zoepage** [comment]
shall we move this to discuss @gr2m ?

**Comment by svnlto** [comment]
> shall we move this to discuss @gr2m ?

my thoughts as well.

**Comment by gr2m** [comment]
this was meant as action item and I thought we agreed on doing it. If there are any objections, feel free to move it or just close it, I don't mind

**Comment by zoepage** [comment]
you're right @gr2m.
we just should label it with the right milestone! ;)
done that :)
