### ISSUE TITLE
clarity issue: using 'couch' as an example type

### ISSUE THREAD

**Issue by bbn** [hoodiehq-archive/hood.ie-website-old#6]
Hi there - congrats on what looks like a cool project.

My small suggestion is that because you're using CouchDB as the backend, you tempt confusion by also using 'couch' in the documentation as the type of object that you're storing. Anything but 'couch' would be better. 'rainbows', for instance.

In fact, I would recommend giving examples with more than one type so that people have a better understanding of how they can segment their data. Maybe 'rainbows' and 'leprechauns'. Or 'coffee' and 'cheesecake'. :)

Ben

**Comment by janl** [comment]
lol, yeah, agreed, in hindsight so obvious, wanna send a PR?

**Comment by janl** [comment]
fixed.
