### ISSUE TITLE
Installation guide recommends running npm with sudo on Linux distributions

### ISSUE THREAD

**Issue by lewiscowper** [hoodiehq-archive/hood.ie-website-old#61]
As the title says, should we still be running the npm install -g hoodie-cli with sudo. I'm guessing not, and I'll submit a pull request if this is the case.

**Comment by varjmes** [comment]
Although this is an issue on the old-website repository, we are still asking users to sudo apt-get on the new websites Installation guide. Is it still the case that we should not be doing this? If so, we should totally get some @lewiscowper magical PR's in.

**Comment by varjmes** [comment]
This might be helpful, http://askubuntu.com/a/147029
