### ISSUE TITLE
IRC page: "we'll be around for about undefined"

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/hood.ie-website-old#73]
![screen shot 2014-07-22 at 18 21 02](https://cloud.githubusercontent.com/assets/39992/3660940/4fff79ce-11bc-11e4-99b5-9bed39550ca7.png)

/cc @espy

**Comment by espy** [comment]
Should be fixed with https://github.com/hoodiehq/hood.ie/commit/fe5ede335433cd6d416fb93fc79ae7147a9020c7

Please re-open if not :)
