### ISSUE TITLE
Hoodie start fails after successful install and ".. new <appname>"

### ISSUE THREAD

**Issue by nborwankar** [hoodiehq-archive/hood.ie-website-old#8]
CouchDB starts up then there's an issue with spawning something, I can't tell.

Here's the transcript

[18:31][nitin@nitinmacbookpro:~]$ mkdir sweatshirt
[18:31][nitin@nitinmacbookpro:~]$ cd sweatshirt/
[18:31][nitin@nitinmacbookpro:~/sweatshirt]$ hoodie new numericc
Creating new hoodie app 'numericc'
Cloning into 'numericc'...
remote: Counting objects: 661, done.
remote: Compressing objects: 100% (491/491), done.
remote: Total 661 (delta 246), reused 546 (delta 131)
Receiving objects: 100% (661/661), 1.64 MiB | 512 KiB/s, done.
Resolving deltas: 100% (246/246), done.
npm WARN engine hoodie-app@0.4.13: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm http GET https://registry.npmjs.org/multicouch
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/local-tld-lib
npm http GET https://registry.npmjs.org/http-proxy
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/nodemailer
npm http GET https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/http-proxy
npm http GET https://registry.npmjs.org/http-proxy/-/http-proxy-0.10.0.tgz
npm http 200 https://registry.npmjs.org/local-tld-lib
npm http GET https://registry.npmjs.org/local-tld-lib/-/local-tld-lib-1.0.1.tgz
npm http 200 https://registry.npmjs.org/multicouch
npm http 304 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/multicouch/-/multicouch-0.2.6.tgz
npm http 200 https://registry.npmjs.org/http-proxy/-/http-proxy-0.10.0.tgz
npm http 200 https://registry.npmjs.org/clone
npm http 200 https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/clone/-/clone-0.1.6.tgz
npm http GET https://registry.npmjs.org/connect/-/connect-2.7.4.tgz
npm http 200 https://registry.npmjs.org/local-tld-lib/-/local-tld-lib-1.0.1.tgz
npm http 200 https://registry.npmjs.org/multicouch/-/multicouch-0.2.6.tgz
npm http 200 https://registry.npmjs.org/clone/-/clone-0.1.6.tgz
npm http 200 https://registry.npmjs.org/connect/-/connect-2.7.4.tgz
npm http 200 https://registry.npmjs.org/nodemailer
npm http GET https://registry.npmjs.org/nodemailer/-/nodemailer-0.3.44.tgz
npm http 200 https://registry.npmjs.org/nodemailer/-/nodemailer-0.3.44.tgz
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-1.2.18.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-1.2.18.tgz
npm http GET https://registry.npmjs.org/cradle
npm http GET https://registry.npmjs.org/when
npm http GET https://registry.npmjs.org/mailcomposer
npm http GET https://registry.npmjs.org/simplesmtp
npm http GET https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/when
npm http GET https://registry.npmjs.org/when/-/when-1.7.1.tgz
npm http 200 https://registry.npmjs.org/cradle
npm http 304 https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/cradle/-/cradle-0.6.5.tgz
npm http 200 https://registry.npmjs.org/when/-/when-1.7.1.tgz
npm http 200 https://registry.npmjs.org/mailcomposer
npm http GET https://registry.npmjs.org/mailcomposer/-/mailcomposer-0.1.31.tgz
npm http 200 https://registry.npmjs.org/cradle/-/cradle-0.6.5.tgz
npm http 200 https://registry.npmjs.org/simplesmtp
npm http GET https://registry.npmjs.org/simplesmtp/-/simplesmtp-0.2.4.tgz
npm http 200 https://registry.npmjs.org/mailcomposer/-/mailcomposer-0.1.31.tgz
npm http 200 https://registry.npmjs.org/simplesmtp/-/simplesmtp-0.2.4.tgz
npm http GET https://registry.npmjs.org/follow
npm http GET https://registry.npmjs.org/vargs/0.1.0
npm http 200 https://registry.npmjs.org/vargs/0.1.0
npm http GET https://registry.npmjs.org/vargs/-/vargs-0.1.0.tgz
npm http 200 https://registry.npmjs.org/follow
npm http GET https://registry.npmjs.org/follow/-/follow-0.8.0.tgz
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/rai
npm http GET https://registry.npmjs.org/xoauth2
npm http 200 https://registry.npmjs.org/vargs/-/vargs-0.1.0.tgz
npm http GET https://registry.npmjs.org/mimelib
npm http GET https://registry.npmjs.org/mime/1.2.9
npm http 200 https://registry.npmjs.org/follow/-/follow-0.8.0.tgz
npm http 200 https://registry.npmjs.org/mimelib
npm http 304 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/mimelib/-/mimelib-0.2.12.tgz
npm http 200 https://registry.npmjs.org/rai
npm http 200 https://registry.npmjs.org/mime/1.2.9
npm http GET https://registry.npmjs.org/mime/-/mime-1.2.9.tgz
npm http GET https://registry.npmjs.org/rai/-/rai-0.1.7.tgz
npm http 200 https://registry.npmjs.org/xoauth2
npm http GET https://registry.npmjs.org/xoauth2/-/xoauth2-0.1.7.tgz
npm http 200 https://registry.npmjs.org/mimelib/-/mimelib-0.2.12.tgz
npm http 200 https://registry.npmjs.org/rai/-/rai-0.1.7.tgz
npm http 200 https://registry.npmjs.org/mime/-/mime-1.2.9.tgz
npm http 200 https://registry.npmjs.org/xoauth2/-/xoauth2-0.1.7.tgz
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/cookie-jar
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/aws-sign
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/cookie-jar
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/aws-sign
npm http 304 https://registry.npmjs.org/forever-agent
npm WARN package.json cookie-jar@0.2.0 No README.md file found!
npm WARN package.json oauth-sign@0.2.0 No README.md file found!
npm http 304 https://registry.npmjs.org/tunnel-agent
npm WARN package.json aws-sign@0.2.0 No README.md file found!
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 200 https://registry.npmjs.org/qs
npm WARN package.json forever-agent@0.2.0 No README.md file found!
npm WARN package.json tunnel-agent@0.2.0 No README.md file found!
npm http GET https://registry.npmjs.org/qs/-/qs-0.5.6.tgz
npm http 200 https://registry.npmjs.org/qs/-/qs-0.5.6.tgz
npm http GET https://registry.npmjs.org/encoding
npm http GET https://registry.npmjs.org/addressparser
npm http 200 https://registry.npmjs.org/addressparser
npm http GET https://registry.npmjs.org/addressparser/-/addressparser-0.1.3.tgz
npm http 200 https://registry.npmjs.org/encoding
npm http GET https://registry.npmjs.org/encoding/-/encoding-0.1.6.tgz
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm http 200 https://registry.npmjs.org/addressparser/-/addressparser-0.1.3.tgz
npm http 200 https://registry.npmjs.org/encoding/-/encoding-0.1.6.tgz
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/iconv-lite/0.2.7
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/hoek
npm http 200 https://registry.npmjs.org/iconv-lite/0.2.7
npm http GET https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.2.7.tgz
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm http 200 https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.2.7.tgz
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm WARN excluding symbolic link app/components/hoodie.admin -> /Users/gregor/.bower/links/hoodie.admin
npm WARN excluding symbolic link node_modules/grunt-contrib-handlebars/node_modules/.bin/handlebars -> ../handlebars/bin/handlebars
npm WARN excluding symbolic link node_modules/grunt-contrib-handlebars/node_modules/handlebars/node_modules/.bin/uglifyjs -> ../uglify-js/bin/uglifyjs
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/http-proxy
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/cookie-jar
npm http GET https://registry.npmjs.org/aws-sign
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/http-proxy
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/cookie-jar
npm http 304 https://registry.npmjs.org/aws-sign
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/forever-agent
npm http 200 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/commander/-/commander-1.1.1.tgz
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/qs
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm http GET https://registry.npmjs.org/buffer-crc32/0.1.1
npm http GET https://registry.npmjs.org/cookie/0.0.5
npm http GET https://registry.npmjs.org/bytes/0.2.0
npm http GET https://registry.npmjs.org/send/0.1.0
npm http GET https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/qs/0.5.1
npm http GET https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/cookie-signature/0.0.1
npm http 200 https://registry.npmjs.org/commander/-/commander-1.1.1.tgz
npm http 200 https://registry.npmjs.org/fresh/0.1.0
npm http 200 https://registry.npmjs.org/buffer-crc32/0.1.1
npm http GET https://registry.npmjs.org/fresh/-/fresh-0.1.0.tgz
npm http GET https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.1.1.tgz
npm http 200 https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/pause/-/pause-0.0.1.tgz
npm http 200 https://registry.npmjs.org/qs/0.5.1
npm http 200 https://registry.npmjs.org/cookie/0.0.5
npm http 200 https://registry.npmjs.org/bytes/0.2.0
npm http GET https://registry.npmjs.org/qs/-/qs-0.5.1.tgz
npm http 200 https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/cookie/-/cookie-0.0.5.tgz
npm http GET https://registry.npmjs.org/bytes/-/bytes-0.2.0.tgz
npm http 200 https://registry.npmjs.org/send/0.1.0
npm http 200 https://registry.npmjs.org/cookie-signature/0.0.1
npm http 200 https://registry.npmjs.org/fresh/-/fresh-0.1.0.tgz
npm http GET https://registry.npmjs.org/formidable/-/formidable-1.0.11.tgz
npm http 200 https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.1.1.tgz
npm http GET https://registry.npmjs.org/send/-/send-0.1.0.tgz
npm http GET https://registry.npmjs.org/cookie-signature/-/cookie-signature-0.0.1.tgz
npm http 200 https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/combined-stream
npm http 200 https://registry.npmjs.org/pause/-/pause-0.0.1.tgz
npm http 200 https://registry.npmjs.org/qs/-/qs-0.5.1.tgz
npm http GET https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/cookie/-/cookie-0.0.5.tgz
npm http 200 https://registry.npmjs.org/formidable/-/formidable-1.0.11.tgz
npm http 200 https://registry.npmjs.org/bytes/-/bytes-0.2.0.tgz
npm http GET https://registry.npmjs.org/debug/-/debug-0.7.2.tgz
npm http 200 https://registry.npmjs.org/send/-/send-0.1.0.tgz
npm http 304 https://registry.npmjs.org/combined-stream
npm http 200 https://registry.npmjs.org/cookie-signature/-/cookie-signature-0.0.1.tgz
npm http 304 https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/debug/-/debug-0.7.2.tgz
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm http 200 https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/utile
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/colors
npm http 200 https://registry.npmjs.org/utile
npm http GET https://registry.npmjs.org/utile/-/utile-0.1.7.tgz
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/mime/1.2.6
npm http 200 https://registry.npmjs.org/utile/-/utile-0.1.7.tgz
npm http 200 https://registry.npmjs.org/mime/1.2.6
npm http 200 https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/mime/-/mime-1.2.6.tgz
npm http GET https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm http 200 https://registry.npmjs.org/mime/-/mime-1.2.6.tgz
npm http 200 https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm http GET https://registry.npmjs.org/i
npm http GET https://registry.npmjs.org/deep-equal
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/wordwrap
npm http 200 https://registry.npmjs.org/deep-equal
npm http 200 https://registry.npmjs.org/i
npm http 200 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http GET https://registry.npmjs.org/i/-/i-0.3.1.tgz
npm http 304 https://registry.npmjs.org/wordwrap
npm http 200 https://registry.npmjs.org/rimraf
npm http 200 https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/ncp/-/ncp-0.2.7.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/i/-/i-0.3.1.tgz
npm http 200 https://registry.npmjs.org/ncp/-/ncp-0.2.7.tgz
hoodie-worker-users@0.0.5 node_modules/hoodie-worker-users
├── clone@0.1.6
├── hoodie-worker@0.0.7 (when-promisify@0.0.2, when@1.7.1, cradle@0.6.5)
└── nodemailer@0.3.44 (optimist@0.3.7, simplesmtp@0.2.4, mailcomposer@0.1.31)

hoodie-app@0.4.13 node_modules/hoodie-app
├── local-tld-lib@1.0.1
├── multicouch@0.2.6 (commander@1.1.1)
├── request@2.16.6 (forever-agent@0.2.0, aws-sign@0.2.0, oauth-sign@0.2.0, tunnel-agent@0.2.0, json-stringify-safe@3.0.0, cookie-jar@0.2.0, node-uuid@1.4.0, mime@1.2.9, qs@0.5.6, form-data@0.0.7, hawk@0.10.2)
├── corsproxy@0.2.11 (http-proxy@0.8.7)
├── connect@2.7.4 (fresh@0.1.0, pause@0.0.1, cookie-signature@0.0.1, bytes@0.2.0, buffer-crc32@0.1.1, cookie@0.0.5, debug@0.7.2, formidable@1.0.11, qs@0.5.1, send@0.1.0)
├── http-proxy@0.10.0 (colors@0.6.0-1, pkginfo@0.2.3, optimist@0.3.7, utile@0.1.7)
├── npm@1.2.18
└── hoodie-pocket@0.0.4
[18:33][nitin@nitinmacbookpro:~/sweatshirt]$ cd numericc/
[18:33][nitin@nitinmacbookpro:~/sweatshirt/numericc(master)]$ hoodie start

> numericc@1.0.0 start /Users/nitin/sweatshirt/numericc
> node node_modules/hoodie-app/lib/hoodie-app.js

Start local couch on port: 6002
CouchDB Started
hoodie server started on port '6001'
CouchDB stop triggered by exit

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:977:11)
    at Process.ChildProcess._handle.onexit (child_process.js:768:34)
npm ERR! numericc@1.0.0 start: `node node_modules/hoodie-app/lib/hoodie-app.js`
npm ERR! `sh "-c" "node node_modules/hoodie-app/lib/hoodie-app.js"` failed with 8
npm ERR! 
npm ERR! Failed at the numericc@1.0.0 start script.
npm ERR! This is most likely a problem with the numericc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/hoodie-app/lib/hoodie-app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls numericc
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/nitin/sweatshirt/numericc
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nitin/sweatshirt/numericc/npm-debug.log
npm ERR! not ok code 0

**Comment by janl** [comment]
Is CouchDB installed in /usr/local/bin?
