### ISSUE TITLE
Change the way we deploy hood.ie, because the current method is terrible

### ISSUE THREAD

**Issue by espy** [hoodiehq-archive/hood.ie-website-old#9]
I'm actually not sure how we would do this. The subfolder thing recommended by and for yeoman (http://yeoman.io/deployment.html) is a problem mainly because we could never get the force push to remote to work.

Either we try and find out what the problem is (preferably with a different repo :D ) or we go another route, if anyone has any suggestions.

**Comment by espy** [comment]
Hm, I just noticed that occasionally, our method with deleting gh-pages produces no downtime. If the time between deleting and recreating the branch is small enough, the page is updated immediately without the 5-10 minute downtime usually associated with a new gh-pages branch. I'll keep an eye on it.

**Comment by janl** [comment]
I haven’t seen the 5-10 minute downtime when I deployed. I usually run things as `delete && push` so they go out right after one another.

**Comment by espy** [comment]
I have an alias for it too, and that usually works fine. I only noticed the downtime again yesterday when gh was so sluggish and the subtree push took about 5 minutes.

**Comment by janl** [comment]
ah, of course :)

**Comment by janl** [comment]
fixed in HEAD
